#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");
const matter = require("gray-matter");
const { marked } = require("marked");

const ROOT = path.resolve(__dirname, "..");
const SOURCE_DIR = path.join(__dirname, "zine-source");
const PROJECTS_DIR = path.join(ROOT, "works", "projects");
const ASSETS_DIR = path.join(ROOT, "works", "assets");
const WORKS_HTML_PATH = path.join(ROOT, "works.html");
const ASSETS_MANIFEST_PATH = path.join(__dirname, ".works-assets-manifest.json");

const GRID_START = "<!-- WORKS_GRID_START (auto-generated by zine-builder/build-works.js, do not hand-edit between these markers) -->";
const GRID_END = "<!-- WORKS_GRID_END -->";

const NOTE_FILENAMES = ["index.md", "note.md"];

function escapeHtml(str) {
  return String(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

// Folders can be named "01.MyProject" so their position in the Obsidian
// sidebar controls grid order without needing an "order" field in
// frontmatter. This pulls that leading number out.
const ORDER_PREFIX_RE = /^(\d+)\.\s*/;

function orderFromFolderName(name) {
  const m = name.match(ORDER_PREFIX_RE);
  return m ? parseInt(m[1], 10) : null;
}

function stripOrderPrefix(name) {
  return name.replace(ORDER_PREFIX_RE, "");
}

// Folder names are free text in Obsidian (spaces, punctuation, Korean, etc.)
// but slugs end up in a URL path, so default slugs are sanitized to be
// URL-safe (spaces -> underscore, drop characters that break URLs/paths)
// while keeping non-ASCII letters (Korean, etc.) intact. A leading "NN."
// ordering prefix is dropped first since it's about position, not identity.
// An explicit "slug" in frontmatter always wins over this default.
function slugifyFolderName(name) {
  const cleaned = stripOrderPrefix(name)
    .trim()
    .replace(/\s+/g, "_")
    .replace(/[\/\\:*?"<>|#%&{}$!'@+`=]/g, "");
  return cleaned || "untitled";
}

// Every link in this content type (body + meta) uses the site's shared
// .inline-link style and opens in a new tab, matching the hand-authored pages.
function styleLinks(html) {
  return html.replace(/<a href=/g, '<a target="_blank" class="inline-link" href=');
}

function renderInline(md) {
  if (!md) return "";
  return styleLinks(marked.parseInline(String(md)));
}

function renderBody(md) {
  if (!md) return "";
  return styleLinks(marked.parse(String(md)));
}

function normalizeImages(images) {
  if (!Array.isArray(images)) return [];
  return images.map((img) => {
    if (typeof img === "string") return { src: img, alt: "" };
    return { src: img.src, alt: img.alt || "" };
  });
}

function findNoteFile(folderPath) {
  for (const name of NOTE_FILENAMES) {
    const p = path.join(folderPath, name);
    if (fs.existsSync(p)) return p;
  }
  return null;
}

function loadWorks() {
  if (!fs.existsSync(SOURCE_DIR)) {
    console.log(`[works] source dir not found: ${SOURCE_DIR}`);
    return [];
  }

  const allEntries = fs.readdirSync(SOURCE_DIR, { withFileTypes: true });

  const strayNotes = allEntries.filter((e) => e.isFile() && e.name.toLowerCase().endsWith(".md"));
  for (const stray of strayNotes) {
    console.warn(
      `[works] IGNORING "${stray.name}": it's a loose note directly in zine-source/, not inside its own folder. ` +
        `Move it into a folder (e.g. zine-source/${path.basename(stray.name, ".md")}/index.md) with its images alongside it, or it will never be published.`
    );
  }

  const entries = allEntries.filter((e) => e.isDirectory());
  const works = [];

  for (const entry of entries) {
    const folderName = entry.name;
    const folderPath = path.join(SOURCE_DIR, folderName);
    const notePath = findNoteFile(folderPath);

    if (!notePath) {
      console.log(`[works] skipping "${folderName}": no index.md found`);
      continue;
    }

    const raw = fs.readFileSync(notePath, "utf8");
    let parsed;
    try {
      parsed = matter(raw);
    } catch (err) {
      console.warn(`[works] skipping "${folderName}": failed to parse frontmatter (${err.message})`);
      continue;
    }

    const data = parsed.data || {};

    if (data.publish !== true) {
      console.log(`[works] skipping "${folderName}" (publish is not true)`);
      continue;
    }

    if (!data.title || !data.cover || !Array.isArray(data.images) || data.images.length === 0) {
      console.warn(`[works] skipping "${folderName}": needs "title", "cover", and a non-empty "images" list in frontmatter`);
      continue;
    }

    const slug = data.slug ? String(data.slug).trim() : slugifyFolderName(folderName);
    const cover = String(data.cover).trim();

    if (!fs.existsSync(path.join(folderPath, cover))) {
      console.warn(`[works] skipping "${folderName}": cover file "${cover}" not found next to the note`);
      continue;
    }

    const images = normalizeImages(data.images);
    const missingImage = images.find((img) => !fs.existsSync(path.join(folderPath, img.src)));
    if (missingImage) {
      console.warn(`[works] skipping "${folderName}": image "${missingImage.src}" not found next to the note`);
      continue;
    }

    works.push({
      folderName,
      folderPath,
      slug,
      title: String(data.title).trim(),
      projectTitle: data.projectTitle ? String(data.projectTitle).trim() : String(data.title).trim(),
      meta: data.meta ? String(data.meta).trim() : "",
      cover,
      images,
      order: typeof data.order === "number" ? data.order : orderFromFolderName(folderName) ?? 9999,
      bodyMarkdown: parsed.content,
    });
  }

  works.sort((a, b) => a.order - b.order || a.title.localeCompare(b.title));

  const seenSlugs = new Map();
  for (const w of works) {
    if (seenSlugs.has(w.slug)) {
      console.warn(`[works] duplicate slug "${w.slug}" ("${w.folderName}" vs "${seenSlugs.get(w.slug)}") — overwriting`);
    }
    seenSlugs.set(w.slug, w.folderName);
  }

  return works;
}

function renderGridCard(work) {
  const coverExt = path.extname(work.cover);
  const assetFilename = `${work.slug}${coverExt}`;
  return `<div class="work-card">
<img class="img-gray" src="works/assets/${assetFilename}">
<img class="img-color" src="works/assets/${assetFilename}">
<a href="works/projects/${work.slug}/${work.slug}.html" class="work-text">
${escapeHtml(work.title)}
</a>
</div>`;
}

function renderProjectPage(work) {
  const imgTags = work.images
    .map((img) => (img.alt ? `        <img src="${img.src}" alt="${escapeHtml(img.alt)}">` : `        <img src="${img.src}" >`))
    .join("\n");

  const metaHtml = work.meta ? renderInline(work.meta) : "";
  const bodyHtml = renderBody(work.bodyMarkdown);
  const friendlySlug = work.slug.toLowerCase();

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escapeHtml(work.title)}</title>

<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,200..800&family=Manrope:wght@200..800&display=swap" rel="stylesheet">

<link rel="stylesheet" href="../pages.css">

</head>

<body>

<nav class="navbar">
    <a href="/works.html">Works</a>
</nav>

<section class="slider">
    <div class="slides">
${imgTags}
    </div>
</section>

<section class="text-wrapper">
    <div class="project-title">${escapeHtml(work.projectTitle)}</div>
    <div class="project-meta">${metaHtml}</div>
${bodyHtml}
</section>

<script>
document.addEventListener('contextmenu', function(e) {
    e.preventDefault();
});
// ---------------------- PC 휠 슬라이드 ----------------------
const slides = document.querySelectorAll('.slides');

slides.forEach(slider => {
    const slideImages = slider.querySelectorAll('img');
    let currentIndex = 0;
    const maxIndex = slideImages.length - 1;

    if(window.innerWidth > 768){
        window.addEventListener('wheel', e => {
            if (!slider.contains(e.target)) return;

            const delta = e.deltaY;

            if ((delta > 0 && currentIndex < maxIndex) || (delta < 0 && currentIndex > 0)) {
                e.preventDefault();
                currentIndex = delta > 0
                    ? Math.min(currentIndex + 1, maxIndex)
                    : Math.max(currentIndex - 1, 0);
                slider.style.transform = \`translateX(-\${currentIndex * 100}%)\`;
            }

            if ((currentIndex === maxIndex && delta > 0) || (currentIndex === 0 && delta < 0)) {
                document.body.style.overflowY = 'auto';
            } else {
                document.body.style.overflowY = 'hidden';
            }
        });
    }
});

// ---------------------- 모바일 슬라이드 + 세로스크롤 제어 ----------------------
if(window.innerWidth <= 768){
    slides.forEach(slider => {
        function updateVerticalScrollLock() {
            const atStart = slider.scrollLeft <= 2;
            const atEnd = slider.scrollLeft + slider.clientWidth >= slider.scrollWidth - 2;

            if (atStart || atEnd) {
                document.body.style.overflowY = 'auto';
            } else {
                document.body.style.overflowY = 'hidden';
            }
        }

        slider.addEventListener('scroll', updateVerticalScrollLock);
        updateVerticalScrollLock();
    });
}

if (window.location.pathname === "/works/projects/${work.slug}/${work.slug}.html") {
  window.history.replaceState({}, "", "/works/${friendlySlug}");
}

</script>

</body>
</html>
`;
}

function copyWorkAssets(work) {
  const outDir = path.join(PROJECTS_DIR, work.slug);
  fs.rmSync(outDir, { recursive: true, force: true });
  fs.mkdirSync(outDir, { recursive: true });

  for (const img of work.images) {
    fs.copyFileSync(path.join(work.folderPath, img.src), path.join(outDir, img.src));
  }

  const coverExt = path.extname(work.cover);
  const assetFilename = `${work.slug}${coverExt}`;
  fs.mkdirSync(ASSETS_DIR, { recursive: true });
  fs.copyFileSync(path.join(work.folderPath, work.cover), path.join(ASSETS_DIR, assetFilename));
  return assetFilename;
}

// Tracks which files under works/assets/ this script itself created, so a
// renamed slug's old cover image can be cleaned up on the next build without
// ever touching hand-placed files (audio, etc.) that aren't in the manifest.
function loadAssetManifest() {
  if (!fs.existsSync(ASSETS_MANIFEST_PATH)) return [];
  try {
    return JSON.parse(fs.readFileSync(ASSETS_MANIFEST_PATH, "utf8"));
  } catch {
    return [];
  }
}

function saveAssetManifest(filenames) {
  fs.writeFileSync(ASSETS_MANIFEST_PATH, JSON.stringify(filenames, null, 2), "utf8");
}

function cleanStaleManagedAssets(currentFilenames) {
  const previouslyManaged = loadAssetManifest();
  const currentSet = new Set(currentFilenames);
  for (const filename of previouslyManaged) {
    if (!currentSet.has(filename)) {
      const filePath = path.join(ASSETS_DIR, filename);
      if (fs.existsSync(filePath)) {
        fs.rmSync(filePath);
        console.log(`[works] removed stale asset works/assets/${filename} (no longer referenced)`);
      }
    }
  }
}

function updateWorksGrid(works) {
  if (!fs.existsSync(WORKS_HTML_PATH)) {
    throw new Error(`works.html not found at ${WORKS_HTML_PATH}`);
  }

  let html = fs.readFileSync(WORKS_HTML_PATH, "utf8");
  const startIdx = html.indexOf(GRID_START);
  const endIdx = html.indexOf(GRID_END);

  if (startIdx === -1 || endIdx === -1) {
    throw new Error(
      `works.html is missing the ${GRID_START} / ${GRID_END} markers. Add them around the .work-card list inside .works-grid so this script knows what to replace.`
    );
  }

  const cards = works.map(renderGridCard).join("\n\n");
  const newBlock = `${GRID_START}\n${cards}\n${GRID_END}`;

  html = html.slice(0, startIdx) + newBlock + html.slice(endIdx + GRID_END.length);
  fs.writeFileSync(WORKS_HTML_PATH, html, "utf8");
}

function cleanGeneratedProjectFolders(currentSlugs) {
  if (!fs.existsSync(PROJECTS_DIR)) return;
  const existing = fs.readdirSync(PROJECTS_DIR, { withFileTypes: true }).filter((e) => e.isDirectory());
  for (const dir of existing) {
    if (!currentSlugs.has(dir.name)) {
      fs.rmSync(path.join(PROJECTS_DIR, dir.name), { recursive: true, force: true });
      console.log(`[works] removed stale project folder works/projects/${dir.name}/ (no longer published)`);
    }
  }
}

function build() {
  const works = loadWorks();
  const currentSlugs = new Set(works.map((w) => w.slug));

  cleanGeneratedProjectFolders(currentSlugs);

  const currentAssetFilenames = [];
  for (const work of works) {
    const assetFilename = copyWorkAssets(work);
    currentAssetFilenames.push(assetFilename);
    const outPath = path.join(PROJECTS_DIR, work.slug, `${work.slug}.html`);
    fs.writeFileSync(outPath, renderProjectPage(work), "utf8");
    console.log(`[works] built works/projects/${work.slug}/${work.slug}.html`);
  }

  cleanStaleManagedAssets(currentAssetFilenames);
  saveAssetManifest(currentAssetFilenames);

  updateWorksGrid(works);
  console.log(`[works] updated works.html grid (${works.length} work${works.length === 1 ? "" : "s"})`);
}

build();
